[package]
name = "shared_data"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.47"

# Only compile in the web-time dependency when targeting wasm32
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = "0.2"